#! /bin/sh

# System V init script for chrony
# Adapted from the script already in meta-networking for ntpd

### BEGIN INIT INFO
# Provides:        chrony
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start chrony time daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/bin:/usr/sbin
CFG_FILE=/mnt/iris/chrony/chrony.conf
DAEMON=/usr/sbin/chronyd
PIDFILE=/run/chrony/chronyd.pid

SETUP_SCRIPT="setup-chrony.sh"

test -x $DAEMON -a -r ${CFG_FILE} || exit 0

# Source function library.
. /etc/init.d/functions

# Functions to do individual actions
startdaemon(){
	if [ -x "/usr/bin/${SETUP_SCRIPT}" ]; then
		echo "chronyd: Running setup script: $SETUP_SCRIPT"
		"/usr/bin/${SETUP_SCRIPT}"
	fi
	echo -n "Starting chronyd: "
	start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON -- "$@" -f ${CFG_FILE}
	echo "done"
}
stopdaemon(){
	echo -n "Stopping chronyd: "
	start-stop-daemon --stop --quiet --oknodo -p $PIDFILE
	echo "done"
}

case "$1" in
  start)
	startdaemon
	;;
  stop)
  	stopdaemon
	;;
  force-reload | restart | reload)
  	stopdaemon
	startdaemon
	;;
  status)
	status /usr/sbin/chronyd;
	exit $?
	;;
  *)
	echo "Usage: chronyd { start | stop | status | restart | reload }" >&2
	exit 1
	;;
esac

exit 0
