#!/bin/sh

LAZY_RESET_FLAG="/etc/counter/lazy_factory_reset"

print_info() {
    [ "$1" -eq 0 ] && printf "GOOD"
    [ "$1" -eq 1 ] && printf "OPEN"
    [ "$1" -eq 2 ] && printf "SHORT"
    [ "$1" -eq 3 ] && printf "TEST FAILED"
}

set_flag() {
	touch "$LAZY_RESET_FLAG"
}

is_flag_set() {
	[ -f "$LAZY_RESET_FLAG" ] && return 0
	return 1
}

cable_test_wait_for_completion() {
    j=5
    while [ "$j" -gt 0 ]; do
        usleep 30
        status=$(phytool read eth0/0x1/0x001D)
        [ $((status & 0x8000)) -ne 0 ] || break
        j=$((j-1))
    done
    [ "$j" -gt 0 ] || { echo "[ERROR] self cleared failed -> timeout: $status"; return 1; }
    return 0
}

read_one_pair() {
    # set mdi/mdix
    if [ "$1" -eq 0 ]; then
        phytool write eth0/0x1/0x001F 0xA100 # Disbale auto MDI/MDI-X + set MDI
    else
        phytool write eth0/0x1/0x001F 0xE100 # Disbale auto MDI/MDI-X + set MDIX
    fi
    phytool write eth0/0x1/0x001D 0x8000 # Start cable diagnostic
    cable_test_wait_for_completion || return 1

    ret=$(((status>>13)&0x3))
    [ "$ret" -eq 3 ] && return 1 # test failed
    echo "$ret"
    return 0
}

# KSZ8081 short detection
# Test if the cable pairs 1/2 and 3/6 are shorted
# returns 0 on short, 1 otherwise
short_detected() {
    echo "Start KSZ8081 short check"

    PHY_ID_KSZRNB=0x00221561
    id1=$(phytool read eth0/0x1/0x0002)
    id2=$(phytool read eth0/0x1/0x0003)
    id=$(printf '0x%.8X\n' "$(((id1 << 16) | id2))")
    [ "$((id))" -eq "$((PHY_ID_KSZRNB))" ] || { echo "Error: PHY ID is not supported"; return 1; }

    # Prepare
    phytool write eth0/0x1/0x0000 0x0100 # Disable Autonegotiation + 10Mbps

    # The cable diagnostic might fail due to active link partner.
    # Try harder if link partner is active.
    i=0
    while [ $i -lt 20 ]; do
        # read_one_pair 0: test pair 1/2
        # read_one_pair 1: test pair 3/6
        pair_a=$(read_one_pair 0) && pair_b=$(read_one_pair 1) && break
        i=$(( i + 1 ))
    done

    # Reset
    phytool write eth0/0x1/0x001F 0x8100 # Enable auto MDI/MDI-X
    phytool write eth0/0x1/0x0000 0x3100 # Enable autonegotiation + 100Mbps

    [ "$i" -lt 20 ] || { echo "Error: Max retries reached"; return 1; }

    echo "  A: $pair_a $(print_info "$pair_a")"
    echo "  B: $pair_b $(print_info "$pair_b")"

    if [ "$pair_a" -eq 2 ] && [ "$pair_b" -eq 2 ]; then
        return 0
    fi

    return 1
}

reset_systemtime() {
    date_string=$(cat /etc/timestamp)
    year=$(echo "$date_string" | cut -c 1-4)
    month=$(echo "$date_string" | cut -c 5-6)
    day=$(echo "$date_string" | cut -c 7-8)
    hour=$(echo "$date_string" | cut -c 9-10)
    minute=$(echo "$date_string" | cut -c 11-12)
    second=$(echo "$date_string" | cut -c 13-14)
    date -s "$year-$month-$day $hour:$minute:$second"
}

reset_userdata() {
    rm -f /etc/counter/config_customer*
    rm -f /etc/counter/config.yaml*
    rm -rf /etc/counter/irma6webserver
    rm -rf /etc/counter/dropbear

    # Delete custom services
    rm -rf /mnt/iris/services/*

    rm -f "$LAZY_RESET_FLAG"
    sync
}

factory_reset() {
    echo "Factory reset!"
    reset_systemtime
    reset_userdata
}
