# rsyslog conf for systemd
# minimal setup -> purely used for remote syslog
# does not create local text files, since information is already available in systemd journal

global(
    DefaultNetstreamDriver="gtls"
    DefaultNetstreamDriverCAFile="/mnt/iris/syslogtls/sensor.crt"
    net.enableDNS="off" # Disable DNS lookups for local hostname
)

$ActionSendStreamDriverAuthMode x509/name # always authenticate the server

# Input modules
$ModLoad immark     # provides --MARK-- message capability
$ModLoad imuxsock   # provides support for local system logging (e.g. via logger command)

# Emergencies to logged-in users
*.emerg :omusrmsg:*

# Syslog template according to RFC5424
$template iris_syslog_format_v1,"<%PRI%>1 %$year%-%$month%-%$day%T%timegenerated:12:19:date-rfc3339%Z %HOSTNAME% %syslogtag%%msg%"

# Include generated read/write config
include(file="/mnt/iris/rsyslog/*.conf" mode="optional")
