#!/bin/sh

set_flag() {
	echo "Error: $0 not implemented"
	return 1
}

is_flag_set() {
	echo "Error: $0 not implemented"
	return 1
}

short_detection_init() {
	:
}

short_detection_deinit() {
	:
}

short_detected() {
	echo "Error: $0 not implemented"
	return 1
}

factory_reset() {
	echo "Error: $0 not implemented"
	return 1
}
