#!/bin/sh

# udhcpc script edited by Tim Riker <Tim@Rikers.org>
# Link to repository https://github.com/mschlenker/TinyCrossLinux/blob/master/patches/usr-share-udhcpc-default.script
# this script is found per default in the directory /etc/udhcp - Just the session "iris modification for reading DHCP option 42" modified by iris GmbH when customer use option 42 per DHCP Server

echo "Starting /etc/udhcp.d/50default"
[ -z "$1" ] && echo "Error: should be called from udhcpc" && exit 1

RESOLV_CONF="/etc/resolv.conf"
[ -n "$subnet" ] && NETMASK="netmask $subnet"

# return 0 if root is mounted on a network filesystem
root_is_nfs() {
	sed -n 's/^[^ ]* \([^ ]*\) \([^ ]*\) .*$/\1 \2/p' /proc/mounts |
	grep -q "^/ \(nfs\|smbfs\|ncp\|coda\)$"
}

have_bin_ip=0
if [ -x /sbin/ip ]; then
  have_bin_ip=1
  BROADCAST="broadcast +"
fi

[ -n "$broadcast" ] && BROADCAST="broadcast $broadcast"

case "$1" in
	deconfig)
		if [ -x /sbin/resolvconf ]; then
			/sbin/resolvconf -d "${interface}.udhcpc"
		fi
		if ! root_is_nfs ; then
                        if [ $have_bin_ip -eq 1 ]; then
                                /sbin/ip -4 addr flush dev $interface
                                /sbin/ip link set dev $interface up
                        else
                                /sbin/ifconfig $interface 0.0.0.0
                        fi
		fi
		;;

	renew|bound)
                if [ $have_bin_ip -eq 1 ]; then
                        /sbin/ip addr add dev $interface local $ip/$mask $BROADCAST
                else
                        /sbin/ifconfig $interface $ip $BROADCAST $NETMASK
                fi

		if [ -n "$router" ] ; then
			if ! root_is_nfs ; then
                                if [ $have_bin_ip -eq 1 ]; then
                                        while /sbin/ip route del default dev $interface 2>/dev/null ; do
                                                :
                                        done
                                else
                                        while /sbin/route del default gw 0.0.0.0 dev $interface 2>/dev/null ; do
                                                :
                                        done
                                fi
			fi

			metric=10
			for i in $router ; do
                                if [ $have_bin_ip -eq 1 ]; then
                                        /sbin/ip route add default via $i metric $metric dev $interface
                                else
                                        /sbin/route add default gw $i dev $interface metric $metric 2>/dev/null
                                fi
                                metric=$(($metric + 1))
			done
		fi
		# iris modification for reading DHCP option 42
		# listing ntp server ips at renew/bound and pass the ips to the script read_usedhcpoption42_script.sh for further processing
		if [ -n "$ntpsrv" ] ; then
			echo "The ntpsrv list is not empty. Reading list at renew/bound event"
			/etc/udhcpc.d/dhcp_option_42/read_usedhcpoption42_script.sh "$ntpsrv"
		else
			echo "The ntpsrv list is empty."
		fi
		# reading dhcp option 7 to pass syslog server list to the script and restarting rsyslog service 
		if [ -n "$opt7" ] ; then
			echo "reading dhcp option 7 and call script for restarting rsyslog service"
			/etc/udhcpc.d/dhcp_custom_option/udhcp_custom_syslog_option.sh "$opt7"
		else
			echo "The log server list is empty."
		fi
		# Update resolver configuration file
		R=""
		[ -n "$domain" ] && R="domain $domain"
		for i in $dns; do
			echo "$0: Adding DNS $i"
			R="${R}nameserver $i"
		done

		if [ -x /sbin/resolvconf ]; then
			echo -n "$R" | /sbin/resolvconf -a "${interface}.udhcpc"
		else
			echo -n "$R" > "$RESOLV_CONF"
		fi
		;;
esac

exit 0
