#!/bin/sh

# SPDX-License-Identifier: MIT
# Copyright (C) 2022-2025 iris-GmbH infrared & intelligent sensors

. /usr/share/iris/network-helper-script.sh || exit 1

if [ "$IFACE" = "eth0" ]; then
    echo "Network Configuration Script"
    setupNetworkInterfaces &
fi
