#!/bin/sh
# filename: eth0-pre-up-maintenance
# This script configures an aditional virtual Linux network interface for the maintenance firmaware:
#
# eth0.2: is the maintenance network adapter. It is always in static IP mode with the IP address 192.168.240.254 (only Maintnenace FW)
#         This interface is configured by the /etc/network/interfaces file

createDefaultAdapter(){
   # add virtual network adapter with default ip
   ifconfig eth0:2 192.168.240.254 netmask 255.255.254.0
   echo "Interface 2: using IP: 192.168.240.254"
}

createDefaultAdapter
