#!/bin/sh

cable_is_shorted=0

print_info() {
    [ "$1" -eq 0 ] && printf "GOOD"
    [ "$1" -eq 1 ] && printf "OPEN"
    [ "$1" -eq 2 ] && printf "SHORT"
    [ "$1" -eq 3 ] && printf "TEST FAILED"
}

cable_test_wait_for_completion() {
    j=5
    while [ "$j" -gt 0 ]; do
        usleep 30
        status=$(phytool read eth0/0x1/0x001D)
        [ $((status & 0x8000)) -ne 0 ] || break
        j=$((j-1))
    done
    [ "$j" -gt 0 ] || { echo "[ERROR] self cleared failed -> timeout: $status"; return 1; }
    return 0
}

read_one_pair() {
    # set mdi/mdix
    if [ "$1" -eq 0 ]; then
        phytool write eth0/0x1/0x001F 0xA100 # Disbale auto MDI/MDI-X + set MDI
    else
        phytool write eth0/0x1/0x001F 0xE100 # Disbale auto MDI/MDI-X + set MDIX
    fi
    phytool write eth0/0x1/0x001D 0x8000 # Start cable diagnostic
    cable_test_wait_for_completion || return 1

    ret=$(((status>>13)&0x3))
    [ "$ret" -eq 3 ] && return 1 # test failed
    echo "$ret"
    return 0
}

# KSZ8081 cable diagnostic
# Test if the cable pairs 1/2 and 3/6 are shorted and store the result in the
# variable: cable_is_shorted: 0: Not shorted, 1: Shorted
# returns 0 on success, 1 otherwise
cable_diagnostic() {
    echo "Start KSZ8081 short check"

    PHY_ID_KSZRNB=0x00221561
    id1=$(phytool read eth0/0x1/0x0002)
    id2=$(phytool read eth0/0x1/0x0003)
    id=$(printf '0x%.8X\n' "$(((id1 << 16) | id2))")
    [ "$((id))" -eq "$((PHY_ID_KSZRNB))" ] || { echo "Error: PHY ID is not supported"; return 1; }

    # Prepare
    phytool write eth0/0x1/0x0000 0x0100 # Disable Autonegotiation + 10Mbps

    # The cable diagnostic might fail due to active link partner.
    # Try harder if link partner is active.
    i=0
    while [ $i -lt 20 ]; do
        # read_one_pair 0: test pair 1/2
        # read_one_pair 1: test pair 3/6
        pair_a=$(read_one_pair 0) && pair_b=$(read_one_pair 1) && break
        i=$(( i + 1 ))
    done

    # Reset
    phytool write eth0/0x1/0x001F 0x8100 # Enable auto MDI/MDI-X
    phytool write eth0/0x1/0x0000 0x3100 # Enable autonegotiation + 100Mbps

    [ "$i" -lt 20 ] || { echo "Error: Max retries reached"; return 1; }

    echo "  A: $pair_a $(print_info "$pair_a")"
    echo "  B: $pair_b $(print_info "$pair_b")"

    if [ "$pair_a" -eq 2 ] && [ "$pair_b" -eq 2 ]; then
        cable_is_shorted=1
    fi
}

# KSZRNB short detection
# Test if the cable pairs 1/2 and 3/6 are shorted
# Caution: returns 0 on short, 1 otherwise
short_detected() {
    cable_diagnostic || return 1
    [ "$cable_is_shorted" -eq 1 ] && return 0 || return 1
}

factory_reset() {
    echo "Factory reset!"
    rm -f /etc/counter/config_customer*
    rm -f /etc/counter/config.yaml*
}

